# Generated by Django 5.0.1 on 2024-02-13 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2)),
                ('meal', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('drinks', models.TextField(blank=True, default='no drinks', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('3D', '3 Days'), ('5D', '5 Days')], max_length=2)),
                ('overall_notes', models.TextField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('days', models.ManyToManyField(to='meals.daydetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
