# Generated by Django 5.0.1 on 2024-03-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mealtype',
            table='meal_type',
        ),
    ]
