from django.urls import path, include
from rest_framework import routers

from .views import SubscriptionViewSet

# Create a router object
router = routers.DefaultRouter()

# Register the SubscriptionViewSet with the router
router.register('subscriptions', SubscriptionViewSet, basename='subscriptions')

# Include the URL patterns generated by the router
urlpatterns = [
    path('', include(router.urls)),
]
